# Generated by Django 4.0.4 on 2022-10-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='movie',
        ),
    ]
